--
-- PostgreSQL database dump
--

\restrict w1wh6tF9OvTlcQ0pdqha9EkIBtF1S7bmQbMf4pVkSmaP69fIHLwb4LVVpEiiGgk

-- Dumped from database version 14.24
-- Dumped by pg_dump version 17.11

-- Started on 2026-08-21 18:43:36

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 211 (class 1259 OID 19332)
-- Name: client_ecbi; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.client_ecbi (
    id integer NOT NULL,
    code character varying(10) DEFAULT NULL::character varying,
    rs_client character varying(255) NOT NULL,
    sigle character varying(255) NOT NULL,
    adresse character varying(255) DEFAULT NULL::character varying,
    tel character varying(50) DEFAULT NULL::character varying,
    mobile character varying(50) DEFAULT NULL::character varying,
    email character varying(255) DEFAULT NULL::character varying,
    created_at timestamp(0) without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    personne_ressource character varying(255) DEFAULT NULL::character varying,
    type_client_id integer,
    cc character varying(50) DEFAULT NULL::character varying,
    ville character varying(100) DEFAULT NULL::character varying,
    pays character varying(100) DEFAULT NULL::character varying
);


ALTER TABLE public.client_ecbi OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 19331)
-- Name: client_ecbi_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.client_ecbi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_ecbi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 19347)
-- Name: commande; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.commande (
    id integer NOT NULL,
    numero_commande character varying(50) NOT NULL,
    date_commande date NOT NULL,
    conditions text,
    code_client_id integer
);


ALTER TABLE public.commande OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 19346)
-- Name: commande_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.commande ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.commande_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 19325)
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 19356)
-- Name: grille_tarif; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.grille_tarif (
    id integer NOT NULL,
    libelle character varying(100) NOT NULL
);


ALTER TABLE public.grille_tarif OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 19355)
-- Name: grille_tarif_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.grille_tarif ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grille_tarif_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 19500)
-- Name: infos_societe; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.infos_societe (
    id integer NOT NULL,
    raison_sociale character varying(255) NOT NULL,
    sigle character varying(100) DEFAULT NULL::character varying,
    tel character varying(50) DEFAULT NULL::character varying,
    mobile character varying(100) DEFAULT NULL::character varying,
    cc character varying(50) DEFAULT NULL::character varying,
    adresse character varying(255) DEFAULT NULL::character varying,
    rccim character varying(100) DEFAULT NULL::character varying,
    logo character varying(255) DEFAULT NULL::character varying,
    email character varying(255) DEFAULT NULL::character varying,
    type_imposition character varying(50) DEFAULT NULL::character varying,
    centre_impots character varying(100) DEFAULT NULL::character varying
);


ALTER TABLE public.infos_societe OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 19499)
-- Name: infos_societe_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.infos_societe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.infos_societe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 19362)
-- Name: ligne_proforma; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ligne_proforma (
    id integer NOT NULL,
    qte integer NOT NULL,
    prix double precision,
    total double precision,
    code_proforma_id integer,
    code_produit_id integer
);


ALTER TABLE public.ligne_proforma OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 19361)
-- Name: ligne_proforma_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ligne_proforma ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ligne_proforma_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 19410)
-- Name: messenger_messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messenger_messages (
    id bigint NOT NULL,
    body text NOT NULL,
    headers text NOT NULL,
    queue_name character varying(190) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    available_at timestamp(0) without time zone NOT NULL,
    delivered_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


ALTER TABLE public.messenger_messages OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 19409)
-- Name: messenger_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.messenger_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messenger_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 19456)
-- Name: options_ecbi; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.options_ecbi (
    id integer NOT NULL,
    classname character varying(50) NOT NULL,
    libelle character varying(255) NOT NULL,
    type_option character varying(50) NOT NULL,
    value character varying(255) DEFAULT NULL::character varying,
    groupe character varying(100) DEFAULT NULL::character varying
);


ALTER TABLE public.options_ecbi OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 19455)
-- Name: options_ecbi_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.options_ecbi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.options_ecbi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 19370)
-- Name: produit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produit (
    id integer NOT NULL,
    code_produit character varying(20) NOT NULL,
    libelle character varying(255) NOT NULL,
    description text
);


ALTER TABLE public.produit OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 19369)
-- Name: produit_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.produit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 19467)
-- Name: produit_qualite; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produit_qualite (
    id integer NOT NULL,
    code_produit_id integer,
    code_qualite_id integer
);


ALTER TABLE public.produit_qualite OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 19466)
-- Name: produit_qualite_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.produit_qualite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produit_qualite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 19378)
-- Name: proforma; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.proforma (
    id integer NOT NULL,
    numero_proforma character varying(50) NOT NULL,
    date_proforma date NOT NULL,
    total_ht double precision,
    tva double precision,
    remise double precision,
    net_a_payer double precision,
    conditions text,
    code_client_id integer,
    statut character varying(50) DEFAULT NULL::character varying,
    date_livraison date,
    created_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    created_by character varying(255) DEFAULT NULL::character varying,
    id_sys character varying(255) DEFAULT NULL::character varying,
    montant_lettre character varying(255) DEFAULT NULL::character varying
);


ALTER TABLE public.proforma OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 19377)
-- Name: proforma_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.proforma ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proforma_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 19475)
-- Name: qualite; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.qualite (
    id integer NOT NULL,
    libelle character varying(255) NOT NULL
);


ALTER TABLE public.qualite OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 19474)
-- Name: qualite_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.qualite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.qualite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 19387)
-- Name: tarif_produit_grille; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tarif_produit_grille (
    id integer NOT NULL,
    tarif double precision NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    cretated_by character varying(255) NOT NULL,
    en_vigueur boolean,
    code_produit_id integer,
    code_grille_id integer
);


ALTER TABLE public.tarif_produit_grille OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 19386)
-- Name: tarif_produit_grille_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tarif_produit_grille ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tarif_produit_grille_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 19395)
-- Name: type_client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.type_client (
    id integer NOT NULL,
    libelle character varying(100) NOT NULL
);


ALTER TABLE public.type_client OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 19394)
-- Name: type_client_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.type_client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.type_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 19401)
-- Name: user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    email character varying(180) NOT NULL,
    roles json NOT NULL,
    password character varying(255) NOT NULL,
    nom character varying(100) NOT NULL,
    prenoms character varying(255) DEFAULT NULL::character varying
);


ALTER TABLE public."user" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 19400)
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3453 (class 0 OID 19332)
-- Dependencies: 211
-- Data for Name: client_ecbi; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.client_ecbi (id, code, rs_client, sigle, adresse, tel, mobile, email, created_at, created_by, personne_ressource, type_client_id, cc, ville, pays) FROM stdin;
2	223208	PREFECTURE DE POLICE DE SAN PEDFRO	PREFECTURE SP	San Pedro, Côte d'Ivoire		07 45 45 21 10	infos.prefecturesp@gmail.com	2026-08-21 11:52:01	N'DIA ABDOUL AZIZ	KONATE	3	\N	\N	\N
1	934787	COMPAGNIE IVOIRIENNE DE TRANSFORMATION DE CACAO	CITRAC	06, Route de l'aéroport, Zone Industrielle, San-Pedro, RCI		07 78 64 87 76	infos@citrac.ci	2026-08-18 18:54:58	N'DIA ABDOUL AZIZ	HUSSEIN AMER	2	\N	SAN-PEDRO	CÔTE D'IVOIRE
\.


--
-- TOC entry 3455 (class 0 OID 19347)
-- Dependencies: 213
-- Data for Name: commande; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.commande (id, numero_commande, date_commande, conditions, code_client_id) FROM stdin;
\.


--
-- TOC entry 3451 (class 0 OID 19325)
-- Dependencies: 209
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20260818151217	2026-08-18 15:12:26	67
DoctrineMigrations\\Version20260818174805	2026-08-18 17:48:50	12
DoctrineMigrations\\Version20260820171756	2026-08-20 17:18:01	46
DoctrineMigrations\\Version20260820171854	2026-08-20 17:18:57	6
DoctrineMigrations\\Version20260821074457	2026-08-21 07:45:03	161
DoctrineMigrations\\Version20260821152245	2026-08-21 15:22:51	46
DoctrineMigrations\\Version20260821152802	2026-08-21 15:28:06	11
DoctrineMigrations\\Version20260821155952	2026-08-21 15:59:56	11
DoctrineMigrations\\Version20260821163103	2026-08-21 16:31:06	6
DoctrineMigrations\\Version20260821175648	2026-08-21 17:56:53	7
\.


--
-- TOC entry 3457 (class 0 OID 19356)
-- Dependencies: 215
-- Data for Name: grille_tarif; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.grille_tarif (id, libelle) FROM stdin;
1	BETON à RESISTANCE AVEC CPA 42,5
2	BETON à RESISTANCE AVEC CPJ 42,5
3	CLIENTS SERIEUX
4	ORANGE
5	ENTITES GOUVERNEMENTALES
\.


--
-- TOC entry 3479 (class 0 OID 19500)
-- Dependencies: 237
-- Data for Name: infos_societe; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.infos_societe (id, raison_sociale, sigle, tel, mobile, cc, adresse, rccim, logo, email, type_imposition, centre_impots) FROM stdin;
1	ENTREPRISE CONSTRUCTION BUILDING INSIGNE	ECBI	+225 34712547	+2250707029700	1523907	San-Pédro (Zone Industrielle) Rue C. Donwahi	\N	\N	infos@ecbi.ci	REEL NORMAL	SAN-PEDRO
\.


--
-- TOC entry 3459 (class 0 OID 19362)
-- Dependencies: 217
-- Data for Name: ligne_proforma; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ligne_proforma (id, qte, prix, total, code_proforma_id, code_produit_id) FROM stdin;
56	5	55000	275000	25	17
57	10	65500	655000	25	19
58	25	2000	50000	25	10
\.


--
-- TOC entry 3471 (class 0 OID 19410)
-- Dependencies: 229
-- Data for Name: messenger_messages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.messenger_messages (id, body, headers, queue_name, created_at, available_at, delivered_at) FROM stdin;
\.


--
-- TOC entry 3473 (class 0 OID 19456)
-- Dependencies: 231
-- Data for Name: options_ecbi; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.options_ecbi (id, classname, libelle, type_option, value, groupe) FROM stdin;
1	tva	Valeur de la TVA en %	integer	18	FINANCES
2	date_livraison	Nb de jours Maximum avant livraison	integer	3	PRODUCTION
\.


--
-- TOC entry 3461 (class 0 OID 19370)
-- Dependencies: 219
-- Data for Name: produit; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.produit (id, code_produit, libelle, description) FROM stdin;
5	GR 15-25	GRAVILLONS 15-25	GRAVILLONS 15-25
6	M-ORD	MOELLONS ORDINAIRES	MOELLONS ORDINAIRES
7	M-SEL	MOELLONS SELECTIONNES	MOELLONS SELECTIONNES
8	GR-COMPLET	GRAVILLONS COMPLET POUR BETON 0-25	GRAVILLONS COMPLET PRET POUR LE BETON 0-25
9	C12/15	BETON C12/15	
10	C16/20	BETON C16/20	
11	C20/25	BETON C20/25	
12	C25/30	BETON C25/30	
13	C30/37	BETON C30/37	
14	C35/45	BETON C35/45	
15	HDR	HYDROFUGE	
16	HDR	HYDROFUGE	
17	POMPE	POMPE	
1	SB-5	SABLE0-5	
2	GR 0-31.5	GRAVILLONS 0-31.5	
3	GR 5-25	GRAVILLONS 5-25	
4	GR 5-15	GRAVILLONS 5-15	
18	T-ECR	TEST D"ECRASEMENT	
19	DL	DALLE	
\.


--
-- TOC entry 3475 (class 0 OID 19467)
-- Dependencies: 233
-- Data for Name: produit_qualite; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.produit_qualite (id, code_produit_id, code_qualite_id) FROM stdin;
\.


--
-- TOC entry 3463 (class 0 OID 19378)
-- Dependencies: 221
-- Data for Name: proforma; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.proforma (id, numero_proforma, date_proforma, total_ht, tva, remise, net_a_payer, conditions, code_client_id, statut, date_livraison, created_at, created_by, id_sys, montant_lettre) FROM stdin;
25	257191	2026-08-21	980000	176400	100000	1056400	\N	1	\N	2026-08-24	2026-08-21 18:09:28	N'DIA ABDOUL AZIZ	7RDOFHXLVT3SOIVDTH4PDJDU5ZVQUC0FLLNJVEOHXDL6588A6OI*XKCZZZKVMU25	un million cinquante-six mille quatre cent
\.


--
-- TOC entry 3477 (class 0 OID 19475)
-- Dependencies: 235
-- Data for Name: qualite; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.qualite (id, libelle) FROM stdin;
2	BETON à RESISTANCE AVEC CPJ 42,5
1	BETON à RESISTANCE AVEC CPA 42,5
\.


--
-- TOC entry 3465 (class 0 OID 19387)
-- Dependencies: 223
-- Data for Name: tarif_produit_grille; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tarif_produit_grille (id, tarif, created_at, cretated_by, en_vigueur, code_produit_id, code_grille_id) FROM stdin;
1	55000	2026-08-18 18:38:41	N'DIA ABDOUL AZIZ	\N	9	1
2	61500	2026-08-18 18:41:51	N'DIA ABDOUL AZIZ	\N	10	1
3	65500	2026-08-18 18:42:30	N'DIA ABDOUL AZIZ	\N	11	1
4	68000	2026-08-18 18:42:46	N'DIA ABDOUL AZIZ	\N	12	1
5	73000	2026-08-18 18:43:02	N'DIA ABDOUL AZIZ	\N	13	1
6	81000	2026-08-18 18:43:22	N'DIA ABDOUL AZIZ	\N	14	1
7	3000	2026-08-18 18:44:04	N'DIA ABDOUL AZIZ	\N	15	1
8	3000	2026-08-18 18:44:21	N'DIA ABDOUL AZIZ	\N	16	1
9	2000	2026-08-18 18:44:38	N'DIA ABDOUL AZIZ	\N	17	1
10	70000	2026-08-18 18:44:56	N'DIA ABDOUL AZIZ	\N	18	1
11	60000	2026-08-18 18:49:32	N'DIA ABDOUL AZIZ	\N	19	2
12	52000	2026-08-19 12:40:19	N'DIA ABDOUL AZIZ	\N	9	2
13	50000	2026-08-19 14:51:24	N'DIA ABDOUL AZIZ	\N	9	3
14	22000	2026-08-19 16:20:32	N'DIA ABDOUL AZIZ	\N	6	3
15	40000	2026-08-19 16:21:43	N'DIA ABDOUL AZIZ	\N	14	3
16	15000	2026-08-19 16:22:51	N'DIA ABDOUL AZIZ	\N	14	3
17	35000	2026-08-19 17:25:12	N'DIA ABDOUL AZIZ	\N	10	3
18	55000	2026-08-20 11:20:58	N'DIA ABDOUL AZIZ	\N	9	4
19	45000	2026-08-20 11:21:17	N'DIA ABDOUL AZIZ	\N	14	4
20	51000	2026-08-21 11:52:59	N'DIA ABDOUL AZIZ	\N	9	5
21	47000	2026-08-21 11:53:44	N'DIA ABDOUL AZIZ	\N	11	5
22	22500	2026-08-21 11:53:56	N'DIA ABDOUL AZIZ	\N	1	5
\.


--
-- TOC entry 3467 (class 0 OID 19395)
-- Dependencies: 225
-- Data for Name: type_client; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.type_client (id, libelle) FROM stdin;
1	PARTICULIER
2	ENTREPRISE
3	GOUVERNEMENT
4	ONG
\.


--
-- TOC entry 3469 (class 0 OID 19401)
-- Dependencies: 227
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."user" (id, email, roles, password, nom, prenoms) FROM stdin;
1	aziz.ndia@citrac.ci	["ROLE_ADMIN","ROLE_USER"]	$2y$13$O1I9gqD6xnJF.AIK7yZy9.y5qGrLCRhZy9gURVCBaHBBKMOx863u.	N'DIA	ABDOUL AZIZ
\.


--
-- TOC entry 3486 (class 0 OID 0)
-- Dependencies: 210
-- Name: client_ecbi_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.client_ecbi_id_seq', 2, true);


--
-- TOC entry 3487 (class 0 OID 0)
-- Dependencies: 212
-- Name: commande_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.commande_id_seq', 1, false);


--
-- TOC entry 3488 (class 0 OID 0)
-- Dependencies: 214
-- Name: grille_tarif_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.grille_tarif_id_seq', 5, true);


--
-- TOC entry 3489 (class 0 OID 0)
-- Dependencies: 236
-- Name: infos_societe_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.infos_societe_id_seq', 1, true);


--
-- TOC entry 3490 (class 0 OID 0)
-- Dependencies: 216
-- Name: ligne_proforma_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ligne_proforma_id_seq', 58, true);


--
-- TOC entry 3491 (class 0 OID 0)
-- Dependencies: 228
-- Name: messenger_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.messenger_messages_id_seq', 1, false);


--
-- TOC entry 3492 (class 0 OID 0)
-- Dependencies: 230
-- Name: options_ecbi_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.options_ecbi_id_seq', 2, true);


--
-- TOC entry 3493 (class 0 OID 0)
-- Dependencies: 218
-- Name: produit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.produit_id_seq', 19, true);


--
-- TOC entry 3494 (class 0 OID 0)
-- Dependencies: 232
-- Name: produit_qualite_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.produit_qualite_id_seq', 1, false);


--
-- TOC entry 3495 (class 0 OID 0)
-- Dependencies: 220
-- Name: proforma_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.proforma_id_seq', 25, true);


--
-- TOC entry 3496 (class 0 OID 0)
-- Dependencies: 234
-- Name: qualite_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.qualite_id_seq', 2, true);


--
-- TOC entry 3497 (class 0 OID 0)
-- Dependencies: 222
-- Name: tarif_produit_grille_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tarif_produit_grille_id_seq', 22, true);


--
-- TOC entry 3498 (class 0 OID 0)
-- Dependencies: 224
-- Name: type_client_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.type_client_id_seq', 1, false);


--
-- TOC entry 3499 (class 0 OID 0)
-- Dependencies: 226
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_id_seq', 1, true);


--
-- TOC entry 3265 (class 2606 OID 19344)
-- Name: client_ecbi client_ecbi_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client_ecbi
    ADD CONSTRAINT client_ecbi_pkey PRIMARY KEY (id);


--
-- TOC entry 3268 (class 2606 OID 19353)
-- Name: commande commande_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.commande
    ADD CONSTRAINT commande_pkey PRIMARY KEY (id);


--
-- TOC entry 3263 (class 2606 OID 19330)
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- TOC entry 3271 (class 2606 OID 19360)
-- Name: grille_tarif grille_tarif_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grille_tarif
    ADD CONSTRAINT grille_tarif_pkey PRIMARY KEY (id);


--
-- TOC entry 3302 (class 2606 OID 19514)
-- Name: infos_societe infos_societe_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.infos_societe
    ADD CONSTRAINT infos_societe_pkey PRIMARY KEY (id);


--
-- TOC entry 3275 (class 2606 OID 19366)
-- Name: ligne_proforma ligne_proforma_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ligne_proforma
    ADD CONSTRAINT ligne_proforma_pkey PRIMARY KEY (id);


--
-- TOC entry 3292 (class 2606 OID 19417)
-- Name: messenger_messages messenger_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messenger_messages
    ADD CONSTRAINT messenger_messages_pkey PRIMARY KEY (id);


--
-- TOC entry 3294 (class 2606 OID 19463)
-- Name: options_ecbi options_ecbi_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.options_ecbi
    ADD CONSTRAINT options_ecbi_pkey PRIMARY KEY (id);


--
-- TOC entry 3277 (class 2606 OID 19376)
-- Name: produit produit_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produit
    ADD CONSTRAINT produit_pkey PRIMARY KEY (id);


--
-- TOC entry 3298 (class 2606 OID 19471)
-- Name: produit_qualite produit_qualite_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produit_qualite
    ADD CONSTRAINT produit_qualite_pkey PRIMARY KEY (id);


--
-- TOC entry 3280 (class 2606 OID 19384)
-- Name: proforma proforma_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proforma
    ADD CONSTRAINT proforma_pkey PRIMARY KEY (id);


--
-- TOC entry 3300 (class 2606 OID 19479)
-- Name: qualite qualite_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.qualite
    ADD CONSTRAINT qualite_pkey PRIMARY KEY (id);


--
-- TOC entry 3284 (class 2606 OID 19391)
-- Name: tarif_produit_grille tarif_produit_grille_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tarif_produit_grille
    ADD CONSTRAINT tarif_produit_grille_pkey PRIMARY KEY (id);


--
-- TOC entry 3286 (class 2606 OID 19399)
-- Name: type_client type_client_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.type_client
    ADD CONSTRAINT type_client_pkey PRIMARY KEY (id);


--
-- TOC entry 3289 (class 2606 OID 19407)
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- TOC entry 3269 (class 1259 OID 19354)
-- Name: idx_6eeaa67db5ae1119; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_6eeaa67db5ae1119 ON public.commande USING btree (code_client_id);


--
-- TOC entry 3290 (class 1259 OID 19418)
-- Name: idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON public.messenger_messages USING btree (queue_name, available_at, delivered_at, id);


--
-- TOC entry 3278 (class 1259 OID 19385)
-- Name: idx_8383afd6b5ae1119; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_8383afd6b5ae1119 ON public.proforma USING btree (code_client_id);


--
-- TOC entry 3281 (class 1259 OID 19392)
-- Name: idx_ae017afe279a831d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ae017afe279a831d ON public.tarif_produit_grille USING btree (code_produit_id);


--
-- TOC entry 3282 (class 1259 OID 19393)
-- Name: idx_ae017afe3419515e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ae017afe3419515e ON public.tarif_produit_grille USING btree (code_grille_id);


--
-- TOC entry 3295 (class 1259 OID 19472)
-- Name: idx_ae48dc26279a831d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ae48dc26279a831d ON public.produit_qualite USING btree (code_produit_id);


--
-- TOC entry 3296 (class 1259 OID 19473)
-- Name: idx_ae48dc268e9d7896; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ae48dc268e9d7896 ON public.produit_qualite USING btree (code_qualite_id);


--
-- TOC entry 3266 (class 1259 OID 19345)
-- Name: idx_d514beefad2d2831; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_d514beefad2d2831 ON public.client_ecbi USING btree (type_client_id);


--
-- TOC entry 3272 (class 1259 OID 19368)
-- Name: idx_dc19bee0279a831d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dc19bee0279a831d ON public.ligne_proforma USING btree (code_produit_id);


--
-- TOC entry 3273 (class 1259 OID 19367)
-- Name: idx_dc19bee0fb2a173d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dc19bee0fb2a173d ON public.ligne_proforma USING btree (code_proforma_id);


--
-- TOC entry 3287 (class 1259 OID 19408)
-- Name: uniq_identifier_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uniq_identifier_email ON public."user" USING btree (email);


--
-- TOC entry 3304 (class 2606 OID 19424)
-- Name: commande fk_6eeaa67db5ae1119; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.commande
    ADD CONSTRAINT fk_6eeaa67db5ae1119 FOREIGN KEY (code_client_id) REFERENCES public.client_ecbi(id);


--
-- TOC entry 3307 (class 2606 OID 19439)
-- Name: proforma fk_8383afd6b5ae1119; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proforma
    ADD CONSTRAINT fk_8383afd6b5ae1119 FOREIGN KEY (code_client_id) REFERENCES public.client_ecbi(id);


--
-- TOC entry 3308 (class 2606 OID 19444)
-- Name: tarif_produit_grille fk_ae017afe279a831d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tarif_produit_grille
    ADD CONSTRAINT fk_ae017afe279a831d FOREIGN KEY (code_produit_id) REFERENCES public.produit(id);


--
-- TOC entry 3309 (class 2606 OID 19449)
-- Name: tarif_produit_grille fk_ae017afe3419515e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tarif_produit_grille
    ADD CONSTRAINT fk_ae017afe3419515e FOREIGN KEY (code_grille_id) REFERENCES public.grille_tarif(id);


--
-- TOC entry 3310 (class 2606 OID 19480)
-- Name: produit_qualite fk_ae48dc26279a831d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produit_qualite
    ADD CONSTRAINT fk_ae48dc26279a831d FOREIGN KEY (code_produit_id) REFERENCES public.produit(id);


--
-- TOC entry 3311 (class 2606 OID 19485)
-- Name: produit_qualite fk_ae48dc268e9d7896; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produit_qualite
    ADD CONSTRAINT fk_ae48dc268e9d7896 FOREIGN KEY (code_qualite_id) REFERENCES public.qualite(id);


--
-- TOC entry 3303 (class 2606 OID 19419)
-- Name: client_ecbi fk_d514beefad2d2831; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client_ecbi
    ADD CONSTRAINT fk_d514beefad2d2831 FOREIGN KEY (type_client_id) REFERENCES public.type_client(id);


--
-- TOC entry 3305 (class 2606 OID 19434)
-- Name: ligne_proforma fk_dc19bee0279a831d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ligne_proforma
    ADD CONSTRAINT fk_dc19bee0279a831d FOREIGN KEY (code_produit_id) REFERENCES public.produit(id);


--
-- TOC entry 3306 (class 2606 OID 19429)
-- Name: ligne_proforma fk_dc19bee0fb2a173d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ligne_proforma
    ADD CONSTRAINT fk_dc19bee0fb2a173d FOREIGN KEY (code_proforma_id) REFERENCES public.proforma(id);


--
-- TOC entry 3485 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2026-08-21 18:43:36

--
-- PostgreSQL database dump complete
--

\unrestrict w1wh6tF9OvTlcQ0pdqha9EkIBtF1S7bmQbMf4pVkSmaP69fIHLwb4LVVpEiiGgk

