<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260914160255 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ligne_commande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, qte INT NOT NULL, prix DOUBLE PRECISION DEFAULT NULL, total DOUBLE PRECISION DEFAULT NULL, code_commande_id INT DEFAULT NULL, code_produit_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3170B74BCBABC7E4 ON ligne_commande (code_commande_id)');
        $this->addSql('CREATE INDEX IDX_3170B74B279A831D ON ligne_commande (code_produit_id)');
        $this->addSql('ALTER TABLE ligne_commande ADD CONSTRAINT FK_3170B74BCBABC7E4 FOREIGN KEY (code_commande_id) REFERENCES commande (id)');
        $this->addSql('ALTER TABLE ligne_commande ADD CONSTRAINT FK_3170B74B279A831D FOREIGN KEY (code_produit_id) REFERENCES produit (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ligne_commande DROP CONSTRAINT FK_3170B74BCBABC7E4');
        $this->addSql('ALTER TABLE ligne_commande DROP CONSTRAINT FK_3170B74B279A831D');
        $this->addSql('DROP TABLE ligne_commande');
    }
}
