<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260903090654 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE alertes_users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code_user_id INT DEFAULT NULL, code_alerte_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E5CB15699FC99709 ON alertes_users (code_user_id)');
        $this->addSql('CREATE INDEX IDX_E5CB156980DEDE11 ON alertes_users (code_alerte_id)');
        $this->addSql('CREATE TABLE fichier_commande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) DEFAULT NULL, code_commande_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D68C908ECBABC7E4 ON fichier_commande (code_commande_id)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, lu BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, target VARCHAR(255) DEFAULT NULL, destinataire_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAA4F84F6E ON notification (destinataire_id)');
        $this->addSql('CREATE TABLE pays (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(100) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE programmation_alerte (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_alerte INT NOT NULL, libelle_alerte VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE service_ecbi (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE ville (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) DEFAULT NULL, code_pays_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_43C3D9C39E4306D8 ON ville (code_pays_id)');
        $this->addSql('ALTER TABLE alertes_users ADD CONSTRAINT FK_E5CB15699FC99709 FOREIGN KEY (code_user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE alertes_users ADD CONSTRAINT FK_E5CB156980DEDE11 FOREIGN KEY (code_alerte_id) REFERENCES programmation_alerte (id)');
        $this->addSql('ALTER TABLE fichier_commande ADD CONSTRAINT FK_D68C908ECBABC7E4 FOREIGN KEY (code_commande_id) REFERENCES commande (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA4F84F6E FOREIGN KEY (destinataire_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE ville ADD CONSTRAINT FK_43C3D9C39E4306D8 FOREIGN KEY (code_pays_id) REFERENCES pays (id)');
        $this->addSql('ALTER TABLE client_ecbi ADD rccim VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE client_ecbi ADD bp VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE client_ecbi ADD code_pays_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE client_ecbi ADD CONSTRAINT FK_D514BEEF9E4306D8 FOREIGN KEY (code_pays_id) REFERENCES pays (id)');
        $this->addSql('CREATE INDEX IDX_D514BEEF9E4306D8 ON client_ecbi (code_pays_id)');
        $this->addSql('ALTER TABLE commande ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE commande ADD created_by VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE commande ADD id_sys VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE commande ADD statut VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE commande ADD etat BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE commande ADD code_proforma_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67DFB2A173D FOREIGN KEY (code_proforma_id) REFERENCES proforma (id)');
        $this->addSql('CREATE INDEX IDX_6EEAA67DFB2A173D ON commande (code_proforma_id)');
        $this->addSql('ALTER TABLE proforma ADD taux_remise INT DEFAULT NULL');
        $this->addSql('ALTER TABLE proforma ADD duree_validite INT DEFAULT NULL');
        $this->addSql('ALTER TABLE proforma ADD rejet BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD titre VARCHAR(25) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD fonction VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD mobile VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD code_service_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649C5F25400 FOREIGN KEY (code_service_id) REFERENCES service_ecbi (id)');
        $this->addSql('CREATE INDEX IDX_8D93D649C5F25400 ON "user" (code_service_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE alertes_users DROP CONSTRAINT FK_E5CB15699FC99709');
        $this->addSql('ALTER TABLE alertes_users DROP CONSTRAINT FK_E5CB156980DEDE11');
        $this->addSql('ALTER TABLE fichier_commande DROP CONSTRAINT FK_D68C908ECBABC7E4');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAA4F84F6E');
        $this->addSql('ALTER TABLE ville DROP CONSTRAINT FK_43C3D9C39E4306D8');
        $this->addSql('DROP TABLE alertes_users');
        $this->addSql('DROP TABLE fichier_commande');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE pays');
        $this->addSql('DROP TABLE programmation_alerte');
        $this->addSql('DROP TABLE service_ecbi');
        $this->addSql('DROP TABLE ville');
        $this->addSql('ALTER TABLE client_ecbi DROP CONSTRAINT FK_D514BEEF9E4306D8');
        $this->addSql('DROP INDEX IDX_D514BEEF9E4306D8');
        $this->addSql('ALTER TABLE client_ecbi DROP rccim');
        $this->addSql('ALTER TABLE client_ecbi DROP bp');
        $this->addSql('ALTER TABLE client_ecbi DROP code_pays_id');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67DFB2A173D');
        $this->addSql('DROP INDEX IDX_6EEAA67DFB2A173D');
        $this->addSql('ALTER TABLE commande DROP created_at');
        $this->addSql('ALTER TABLE commande DROP created_by');
        $this->addSql('ALTER TABLE commande DROP id_sys');
        $this->addSql('ALTER TABLE commande DROP statut');
        $this->addSql('ALTER TABLE commande DROP etat');
        $this->addSql('ALTER TABLE commande DROP code_proforma_id');
        $this->addSql('ALTER TABLE proforma DROP taux_remise');
        $this->addSql('ALTER TABLE proforma DROP duree_validite');
        $this->addSql('ALTER TABLE proforma DROP rejet');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649C5F25400');
        $this->addSql('DROP INDEX IDX_8D93D649C5F25400');
        $this->addSql('ALTER TABLE "user" DROP titre');
        $this->addSql('ALTER TABLE "user" DROP fonction');
        $this->addSql('ALTER TABLE "user" DROP mobile');
        $this->addSql('ALTER TABLE "user" DROP code_service_id');
    }
}
